//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIT420COVIDFinalTiffanyValentina
{
    using System;
    using System.Collections.Generic;
    
    public partial class NursingHomeDeathsTable
    {
        public int DeathID { get; set; }
        public System.DateTime Date { get; set; }
        public int LicenseNum { get; set; }
        public string TownName { get; set; }
        public string NursingHome { get; set; }
        public int COVIDPositive { get; set; }
        public int COVIDDeath { get; set; }
        public int ProbableDeath { get; set; }
    
        public virtual NursingHomeIDTable NursingHomeIDTable { get; set; }
    }
}
